### ISSUE TITLE
Correct comment on [not] trivially destructable

### ISSUE THREAD

**Issue by martinmoene** [TartanLlama/optional#12]
Looks like the negation of trivially destructable in [the comments of the storage base class](https://github.com/TartanLlama/optional/blob/35e4c6e88915dc8a98b4601c514114f144e197ab/tl/optional.hpp#L298) should be swapped.

**Comment by TartanLlama** [comment]
Thanks, fixed.

**Comment by martinmoene** [comment]
@TartanLlama Erm, swap implies two locations ;)

**Comment by TartanLlama** [comment]
Whoops, done!
