### ISSUE TITLE
CMake generation fails for Release build with tests on and documentation off

### ISSUE THREAD

**Issue by eyalroz** [TartanLlama/optional#21]
I'm building the package on Devuan ASCII (= Debian Stretch without systemd), with CMake 3.13.1 under `/usr/local/src`, locally built from a source tarball.

I've done the following:

* clone the repo to `/path/to/tl-optional`
* `cd /path/to/tl-optional`
* `ccmake .`
* Set build type to `Release` (I realize that shouldn't matter much)
* Set documentation to OFF
* Configure again
* Generate

and I get:
```
 CMake Error at CMakeLists.txt:34 (add_executable):
   Cannot find source file:

     /path/to/tl-optional/tests/main.cpp

   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
   .hpp .hxx .in .txx


 CMake Error: Cannot determine link language for target "tests".
 CMake Error: CMake can not determine linker language for target: tests
```

**Comment by TartanLlama** [comment]
I can't reproduce this, but did you try building in a subdirectory?

**Comment by eyalroz** [comment]
Can't reproduce with the latest head.
