### ISSUE TITLE
Suggestion: `take()` should always move

### ISSUE THREAD

**Issue by Magnutic** [TartanLlama/optional#23]
Hello, thank you for this library! It does make optional much more pleasant to use.

Since `take()` will always empty the optional it is invoked upon, I expected it to always move. However, I noticed that there are const and non-const / lvalue and rvalue overloads for this function, and only the non-const-rvalue one will move. Is there a particular reason for this? The const overloads are not usable anyway, as `reset()` is non-const.

I suggest replacing all overloads with:

```
  optional take() {
    optional ret = std::move(*this);
    reset();
    return ret;
  }
```

A moving `take()` can be helpful when using optionals of move-only types, for example

```
tl::optional<some_move_only_t> opt = ...;
// ...
some_move_only_t value = opt.take().value();
```
is a bit neater to me than:
```
tl::optional<some_move_only_t> opt = ...;
// ...
some_move_only_t value = std::move(opt).value();
```
Especially since the latter leaves the optional non-empty, but with a moved-from value.
Right now, to get the same effect, you would have to do like so:
```
tl::optional<some_move_only_t> opt = ...;
// ...
some_move_only_t value = std::move(opt).take().value();
```
Which is a bit noisy.

Also, perhaps there is some merit to having a `take_value()` member function that is semantically equivalent to `take().value()` but avoids constructing a temporary optional -- what do you think?

**Comment by TartanLlama** [comment]
Thanks! Sorry it took me a while to address this, but I made the change you suggested.

I'll think about the `take_value`  function.
