### ISSUE TITLE
Current master is broken (cmake error)

### ISSUE THREAD

**Issue by ubruhin** [TartanLlama/optional#32]
Even when running Travis-CI/AppVeyor on the current `master` branch, they fail with the following error:

```
$ mkdir build && cd build && cmake -DCXXSTD=$CXXSTD .. && make && ./tests
-- The CXX compiler identification is GNU 5.5.0
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at build/_deps/tl_cmake-src/add-tl.cmake:6 (target_sources):
  target_sources may only set INTERFACE properties on INTERFACE targets
Call Stack (most recent call first):
  CMakeLists.txt:19 (tl_add_library)
-- Configuring incomplete, errors occurred!
```

Since the same revision passed CI 5 days ago, I suspect it has to do with a change in the `tl-cmake` repository 4 days ago. I have no idea how this CMake stuff works exactly, but in the `CMakeLists.txt` I see a dependency to https://github.com/TartanLlama/tl-cmake.git without specifying an exact revision. This is generally a very bad idea since it's impossible to get stable, reproducible builds.

So I would suggest to link to a specific revision (tag or commit SHA). Or even better, remove the dependency completely :wink:

#31 is currently blocked by this issue since CI always fails.

**Comment by TartanLlama** [comment]
Dependency removed, thanks.
