### ISSUE TITLE
Return type not correctly deduced

### ISSUE THREAD

**Issue by juxeii** [TartanLlama/optional#39]
Consider this code:

```
tl::optional<int> op = 42;
    op.map([](auto i) {
        if (i == 42)
        {
            return tl::make_optional("good");
        }
        return tl::nullopt;
    });
```
This won't compile.
The error message is:
`auto' in return type deduced as 'utils::nullopt_t' here but deduced as 'utils::optional<const char *>' in earlier return statement`
Should't `tl::nullopt` be a value of type` tl::optional<>` for all contained types?

**Comment by TartanLlama** [comment]
That's not possible in the C++ type system unfortunately (at least not off the top of my head). Some options:
Default construct an optional of the correct type
Specify a trailing return type for the lambda
Use a conditional statement (I didn't test this)

**Comment by TartanLlama** [comment]
Oh and it looks like you want and_then instead of map

**Comment by juxeii** [comment]
Ah yes, `and_then` is needed.
Anyway, it is a pitty that C++ has no way of achieving this.
What do you actually mean by "Use a conditional statement"?

**Comment by TartanLlama** [comment]
Like i == 42 ? optional("good") : nullopt;

**Comment by juxeii** [comment]
I remember in Kotlin, there is somethin like `None=Option<Nothing>`
And this `None` is a representation for the generic `Option<>` type constructor.
I wonder why Kotlin is here more powerful than C++.

**Comment by TartanLlama** [comment]
C++ is on a couple decades more history 😄. People are working on proper language sum types, but we're not quite there yet.
