### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by milipili** [TartanLlama/optional#4]
Hi,
Just to let you you something you may already know, all links in https://optional.tartanllama.xyz/ are a dead end :)

**Comment by TartanLlama** [comment]
Yeah, I'm probably misusing the doc generator (standardese) or something. Need to look into it.

**Comment by TartanLlama** [comment]
The docs have now been rewritten from scratch: http://tl.tartanllama.xyz/en/latest/api/optional.html
