### ISSUE TITLE
Plan for new release?

### ISSUE THREAD

**Issue by traversaro** [TartanLlama/optional#46]
Hi @TartanLlama , thanks a lot for the `tl-optional` library.

Do you think it could make sense to have a new tag for this optional library? I was planning to package optional in conda-forge, and I was interested in several bug fixes that are on master but that are not part of the last tag. While I could incorporate them as additional patches on top of the `v1.0.0`, if it is feasible to tag a new version (and bump https://github.com/TartanLlama/optional/blob/master/CMakeLists.txt#L5), it would great to use directly that. 

Let me know if I can help in any way in creating a new tag, thanks!

**Comment by traversaro** [comment]
cc @GiulioRomualdi

**Comment by theShmoo** [comment]
Still interested in a new release!

**Comment by TartanLlama** [comment]
https://github.com/TartanLlama/optional/releases/tag/v1.1.0

**Comment by traversaro** [comment]
Thanks a lot!
